### ISSUE TITLE
data acquisition

### ISSUE THREAD

**Issue by konradmayer** [ECMWFCode4Earth/tesserugged#1]
data is provided by ECMWF via:

- training: https://storage.ecmwf.europeanweather.cloud/Code4Earth/netCDF_era5_1985_2018/t2m_era5_198501_025deg.nc, netCDF_cerra_1985_2018
- verification: https://storage.ecmwf.europeanweather.cloud/Code4Earth/netCDF_era5_2019_2021, netCDF_cerra_2019_2021

**Comment by konradmayer** [comment]
data was downloaded by @ischicker to `/ssea/SSEA/C4E/DATA/XX` to be used internally until the ECMWF computing ressources become available

**Comment by ischicker** [comment]
All data available, training:
/ssea/SSEA/C4E/DATA/XX

testing:
/ssea/SSEA/C4E/DATA/TESTING/XX
