### ISSUE TITLE
weathercloud

### ISSUE THREAD

**Issue by konradmayer** [ECMWFCode4Earth/tesserugged#10]

**Comment by konradmayer** [comment]
# R

@mdaber, @r3xth0r 

we do have three options to define a (preferentially reproducible) R environment on the weather cloud:

- add a DESCRIPTION file and installation via  [`remotes::install_deps`](https://remotes.r-lib.org/reference/install_deps.html) (probably easiest and quick to understand for python-folks as its similar to an environment.yml when usin conda)
- using  [`renv`](https://rstudio.github.io/renv/index.html) (probably overkill)
- using a docker-image

**Comment by r3xth0r** [comment]
All three options are fine with me. Agreed that `remotes::install_deps()` is probably the most straightforward solution. In terms of reproducibility I would usually go with `renv`, but this might indeed be a bit overkill here.
