### ISSUE TITLE
local infrastructure

### ISSUE THREAD

**Issue by konradmayer** [ECMWFCode4Earth/tesserugged#7]
Until ECMWF infrastructure is available, we start developing locally. This issue is used to discuss/document requirements and setup topics

**Comment by konradmayer** [comment]
I start developing on the VM `vcit`, as @seblehner is responsible for this machine I assign this issue to him

**Comment by konradmayer** [comment]
@seblehner, shall we start a new conda env on `vcit` or is there any existing we can hi-jack?

**Comment by seblehner** [comment]
> @seblehner, shall we start a new conda env on `vcit` or is there any existing we can hi-jack?

Most of the existing environments are rather specialized, however, climodlab, htp, or climdex should be fine, depending on what we need. cdo is contained in climdex.

**Comment by konradmayer** [comment]
conda environment `code4earth` was set up, but problems on `vcit` occur due to move of the shared conda environments to `/perm`
